version = 1
SPDX-PackageName = "Vulkan SC Pipeline Cache Utils"
SPDX-PackageSupplier = "The Khronos Group, Inc."
SPDX-PackageDownloadLocation = "https://github.com/KhronosGroup/VulkanSC-pcutil"

[[annotations]]
path = [
    "tests/pcutil/golden_results.txt",
    "tests/json/data/*.json",
    "scripts/known_good.json",
    "json/vk.json",
    "json/vkpcc.json",
    "json/vksc_pipeline_schema.json",
    "layers/json_gen/VkLayer_khronos_json_gen.json.in"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 The Khronos Group, Inc."
SPDX-License-Identifier = "Apache-2.0"
